# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/UrielSerrato/IA/blob/main/Unidad%203%20y%204/Practica1_parte2.ipynb

# Practica 1 - parte 2
Implementar la practica anterior parte 1, reciclar el codigo, para cambiar el tipo de predicción donde realice la conversión diferente (km a m)
"""

import tensorflow as tf
import numpy as np

pie = np.array([5,8,12,20,62], dtype=float)
metro = np.array([1.524,2.4384,3.6576,6.096,18.8976], dtype=float)

#capa = tf.keras.layers.Dense(units=1, input_shape=[1])
#modelo = tf.keras.Sequential([capa])
oculta1 = tf.keras.layers.Dense(units=3, input_shape=[1])
oculta2 = tf.keras.layers.Dense(units=3)
saluda = tf.keras.layers.Dense(units=1)
modelo = tf.keras.Sequential([oculta1,oculta2,salida])

modelo.compile(
    optimizer=tf.keras.optimezers.Adam(0.1),
    loss='mean_squared_error'
)

print("Comenzando entrenamiento...")
historial=modelo.fit(pie,metro,epochs=1000,verbose=False)
print("Modelo entrenado!")

import matplotlib.pyplot as plt
plt.xlabel("Epoca")
plt.ylabel("Magnitud de perdida")
plt.plot(historial.history["loss"])

print("Realizar una predicción!!")
resultado=modelo.predict([50.0])
print("El resultado es" + str(resultado) + "metros")